### ISSUE TITLE
Allow sampling-based timeline view without CPU samples

### ISSUE THREAD

**Issue by felixge** [dominikh/gotraceui#57]
Right now the 	"Toggle displaying sampling-based timelines" (Shortcut `s`) feature only works if the trace contains CPU samples. Would you consider always allowing it? IMO seeing the stack traces for Off-CPU time is very valuable, even if there is no On-CPU breakdown.

I don't mind turning on the CPU profile when using gotraceui, but for some use cases (e.g. running a single test) I can't guarantee that at least one CPU sample will be recorded.

I can try to send a patch for this if you want.

**Comment by felixge** [comment]
That makes sense. When there are no CPU samples showing the CPU time as just "CPU Time" without a stack would be fine for me. I have no strong opinion on defaults, making this a different visualization or just the way the current sampling-based timeline behaves.

**Comment by dominikh** [comment]
I think there is value in having both visualizations. When there are no samples we can of course default to the only available one, but even when there are samples, users might want the other visualization.

Right now, when we have samples, we display stacks from samples as well as a subset of events, primarily blocking ones and preemption points, to increa. There are no gaps between stacks. A stack always continues until we get a new one. This gives us stack timelines that are ~never based on actual events, and instead are sampled (with increased detail at blocking points).

When we don't have samples, we'll display stacks from _all_ events, but events without stacks cause gaps to be created. This is essentially just a graphical representation of event stacks, without further interpretation by us and represents actual raw data. These spans do have width, which does suggest a time component, but we can make it clear that these are instantaneous and that rendering them with no width would be inconvenient.

This new visualization will look something like this:
![image](https://user-images.githubusercontent.com/39825/213552538-bf978d16-3598-4e79-a6bb-8134ea6b5e31.png)

**Comment by whereswaldon** [comment]
I'm aware that it might be a huge pain to add this to the timeline rendering, but to convey the "instantaneousness" of these stacks, could the top of the stack just be a triangle that narrows to a point at the position in the timeline where these samples are from? I think that'd be relatively clear to read.

**Comment by dominikh** [comment]
That would always be a triangle that narrows to the left edge of the span.

**Comment by whereswaldon** [comment]
I figured as much. I still think it would be communicative, but obviously it may not be worth the effort. :D

**Comment by dominikh** [comment]
I am more inclined to change the `Duration` part of the tooltip to say `instantaneous`. The triangle/arrow is a nice idea, but one for the future. It's not worth complicating the rendering for, for now.

**Comment by dominikh** [comment]
@felixge would it be problematic for your use cases if enabling sampling-based tracks happened on a per-goroutine basis, instead of being a global toggle?

**Comment by dominikh** [comment]
I'm experimenting with the following change to sampling/stacks: Always use stacks from all events, never try to fill gaps with the previous stack. Consider the screenshot: Some on-CPU time doesn't have any stacks, because no sample has yet arrived, and because we aren't extending stacks from previous events. This way, it will not look like we're in a blocking function longer than we actually are. This allows us to use stacks from all events; we will no longer attribute too much time to events like GC assist, which would've previously been a source of bias. We're also coloring stacks from samples in a lighter color. Stacks from samples extend until the next event, so their time is approximate, which is different from stacks of blocking events, which are true for the entire duration of the span. 

Of course, during gaps, anything could be happening. But now we're erring on the side of under-representing on-CPU functions, which IMO is less confusing than over-representing it (which we still do for samples, but to a lesser extent.)

![image](https://user-images.githubusercontent.com/39825/213879770-3a7dc4fe-e6dd-4c6d-9ff0-9945e10e9e56.png)

**Comment by felixge** [comment]
> @felixge would it be problematic for your use cases if enabling sampling-based tracks happened on a per-goroutine basis, instead of being a global toggle?

I think there are cases where this would be more convenient and others where it makes navigation more difficult. Would have to play with it, but in general I'd curious to try it out.

I've also just tried out the latest patches. But I don't think I understand how CPU samples are represented now. I would have assumed that they always render as 10ms spans without extending to the previous or next event, but that doesn't seem to be what I'm seeing, for example:

<img width="802" alt="CleanShot 2023-01-22 at 21 41 46@2x" src="https://user-images.githubusercontent.com/15000/213939333-bef86db3-2894-4910-b633-ad65a47ffb6e.png">

Or is this not a CPU sample?

**Comment by dominikh** [comment]
That is a CPU sample. CPU samples start at the point at which the sample occurred and extend until the next event. The next event is either another sample or a transition to some off-CPU state or GC assist. Either one has its own stack that is more accurate than the sample.

**Comment by felixge** [comment]
> CPU samples start at the point at which the sample occurred and extend until the next event

Isn't that the wrong direction? CPU samples are triggered by CPU time that was accumulated between the previous CPU sample for the same thread (linux) and the time that the sample was taken. That makes it difficult to render them, so I'm not sure if there is a correct way of doing it. But I'm curious why you're trying to extrapolate them into the future rather than into the past?

**Comment by dominikh** [comment]
One key issue is that we don't know the sampling rate. It's 100 Hz by default, but the user can adjust it, and the actual value isn't contained in the trace. Without knowing the "length" of a sample, we can't center our span around it, nor decide to extend either to the left or right for a fixed amount of time.

I've chosen to extrapolate them into the future because it's consistent with the stacks of blocking events. We're basically saying "this is the most current stack that we know", and we'll use it until we get another event, which invalidates the previous stack. Transitioning from blocked to running is treated the same as transitioning from sampled to blocked or sampled again.

IMO extrapolating backwards or forwards introduce the same amount of error, just shifted in different directions. Centered around the point would probably be the least incorrect on average, but without the sampling rate, we can't do that. And even if we had the sampling rate (let's assume 100 Hz for the following example), what happens if we transition from blocked to running, and 1 ms into running, we get the sample? We can't extend it to the left and right by 5ms, because that overlaps with the previous event. Doing 1ms and 5ms feels wrong to me, and implies that all samples have different amounts of error, rendered in different ways, with no true center to the sample (and we can't do 1ms and 9ms because that would overlap with the next sample.)

The perfect UI would make it very clear that samples are instantaneous, and that any non-zero length is just to be able to render the labels. We could indicate samples as dots, and only show their stacks in tooltips, similar to what the official UI is doing, but that's poor UX. What we do currently is the equivalent of saying "the sample is here, and we're using the space to the right to render it."

I'd love to know of a better way to render instantaneous events, without needing a third spacial dimension.

**Comment by dominikh** [comment]
The feature you've asked for has been implemented and I am going to close this issue. We can discuss the specifics of the visualization in a separate issue or discussion if anyone has new ideas or feedback.
